### PR TITLE
Add other "each" options

### PR DESCRIPTION
**Pull request by geiseri**
The underlying `Workplane.each(...)` has options to combine and clean the resulting operation on the surface.  In my case doing a 'cut' is much easier to do during the callback instead of trying to merge it together at the end.

### CODE REVIEW

**Comment by jmwright** [comment]
@geiseri  This [pin](https://github.com/CadQuery/cadquery/blob/master/environment.yml#L15) was added to the CQ core to fix the error that I'm seeing with lint. It will probably be easiest if you add it, but I can also add it to main and you can merge that into your branch if you want. It's up to you.

@fedorkotov You implemented this plugin originally. Do you have any thoughts on the changes?

**Comment by geiseri** [comment]
If you could add it that would keep the patch smaller. your call though.

**Comment by jmwright** [comment]
> If you could add it that would keep the patch smaller.

@geiseri Done in #29 . Your lint step should be free of that bug once you have those changes on your branch.

**Comment by jmwright** [comment]
@geiseri The lint check is failing due to a formatting error now.

**Comment by geiseri** [comment]
yeah, sorry just noticed.  should be good now

**Comment by jmwright** [comment]
@geiseri Thanks for the contribution!

**Pull request merged**
