### PR TITLE
Add plugin to create teardrop shape

### PR DESCRIPTION
**Pull request by lorenzncode**
Hi! This request came up on the Discord server.  It is a new plugin for generating teardrop shaped holes for use in 3D printing.

### CODE REVIEW

**Comment by jmwright** [comment]
@lorenzncode Thanks for adding this. Please run the black lint checker against your code. That's keeping the code from passing the checks currently.
```
black --diff --check
```

**Comment by lorenzncode** [comment]
Ran black again - now that should include all three Python files.

**Review by jmwright — APPROVED** [review]
Thanks @lorenzncode

**Comment by martinbudden** [comment]
I think these should be truncated by default, as in https://github.com/nophead/NopSCADlib#Teardrops

**Comment by lorenzncode** [comment]
Thanks for the feedback.  Let's consider this user interface change before merge. I'll also take a look at the approach here https://hydraraptor.blogspot.com/2020/07/horiholes_36.html.

**Comment by martinbudden** [comment]
@lorenzncode , the horiholes used in NopSCADlib are great. I find that when I use NopSCADlib teardrops I never have to drill out holes to make bolts fit etc. I've even found stepper motor bosses have a nice "click fit" with no post processing on the holes. So it is definitely worth going to the effort to replicate this.

**Comment by marcus7070** [comment]
@lorenzncode are you waiting for my review or do you want to do the truncated hole changes first?

**Comment by lorenzncode** [comment]
Before your review, I'd like to:
- change the default to truncated as suggested
- investigate whether to implement some kind of compensation (optionally) similar to blog link above

**Comment by jmwright** [comment]
@lorenzncode  I though this had been merged, sorry about that. Thanks for contributing it.

**Comment by lorenzncode** [comment]
My mistake. I should have marked as draft.  I meant to revisit to address some of the feedback.  Maybe that can be done in a future revision.

**Pull request merged**
